#!/usr/bin/env sh
set -eo pipefail
. "$(dirname -- "$0")/_/husky.sh"

npm run lint-staged

npm run docs:readme:usage
git add README.md

# Check if cliExamples.ts has changed
if git diff --cached --name-only | grep -qE "src/cliExamples\.ts"; then
  npm run docs:readme:examples
  git add README.md
fi

# Check if package.json or .nvmrc has changed
if git diff --cached --name-only | grep -qE "package\.json|\.nvmrc"; then
  npm run update-nvmrc
  git add .nvmrc
fi
